---

etc_hosts_routing: |
  172.30.3.62     o3-master
  172.30.3.74     o3-slave1
  172.30.3.134    o3-slave2
  172.30.3.18     o3-slave3

# TODO(mblomdahl): This could be named better such as allowed networks or something

external_dmz:
  - 37.123.179.154/32 # HQ
  - 213.89.24.38/32   # Carl's Home
  - 10.101.66.0/24
  - 82.96.2.2/32      # SMSI Stockholm Office
  - 82.96.2.60/32     # SMSI Stockholm Office QA
  - 10.110.132.0/24

airflow_admins:
  - mblomdahl
  - cbackstrom

hadoop_admins:
  - mblomdahl
  - cbackstrom

jupyter_admins:
  - mblomdahl
  - cbackstrom

...
