---

etc_hosts_routing: |
  10.192.62.188   o3-master

src_addr_whitelist:
  - 10.192.186.0/24  # SonicWall VPN

hdfs_data_root_path: /data3/hadoop

yarn_nodemanager_resource_memory_mb: 12288
yarn_scheduler_maximum_allocation_mb: 12288

hadoop_admins:
  - mblomdahl
  - cbackstrom

airflow_port: 8090
airflow_admins:
  - mblomdahl
  - cbackstrom

jupyter_admins:
  - mblomdahl
  - cbackstrom

...
