
galaxy_info:
  author: Mats Blomdahl
  description: Provisioning of Apache Airflow.

  min_ansible_version: 2.7

  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - Bionic

  galaxy_tags:
    - airflow

dependencies:
  - python
  - docker
