---

src_addr_whitelist: []

source_branch: master

airflow_admins: []

airflow_port: 8080

airflow_db_user_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34653038373036663735653932373361616132653264656465666365383362306662336237353434
  3132663763333033643530363534613562366262363339660a366133326336653834626165333535
  61613761316532663231346661393731623861613839623965376134323336313334663433363061
  3234663862663330620a656663666365643462646163336532396164306161653961646338626139
  37316132396238383738316232313764643564376236336130326561356637626537

airflow_id_rsa: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31303566363463616264316462326637613933333563373636643734613834343137623636653464
  3839656361386264646639623239643762346565323063370a646562383966626234643130303336
  33303361326536313366366130666564363539363331646162326532353465656335653835316338
  3138373062613662640a623765306531663435363939616435623161663466323563323866363330
  63363637376230396330643939386462376434646265393965306438616236626664363661353436
  30653332366138643861666262386362363937303034616332313865653634396462616265666434
  66363437343634623264386635633965613633356330336438633534643439393431393630313361
  36666661316130326462656663646538316462613663326430323966313664356337303662383432
  34383966323065656435613531393663646437386639396562393931613766363733316338343530
  36346639613133636438336635333761323331303465386434366666333561383634633130646438
  31393831643034306231363965656665643335303136376335316564623939316562316562653864
  31646432613731333532363865343838636161316435373466336332383837343930383366353932
  65353938326665373861383738386530643230643034363030323461626361633635636631666334
  35633631646134366530616261313135363938326131343336643936646234366162376664356431
  64373130633938323938313662653064613831363130383731323530626365376665383436663334
  30396265626264393264333632313062666464393936373634313637643139616631386133363039
  37363838386466373834396162643939643837636463373238333032666231383937393531353066
  34303937643731373835653062366532383266666664386237353063363563393931383937346164
  35346435333063363662633261366666626364643766666365333931646433383961336135313836
  61313861373831343564326165623231623639666137613039623930396430353064613465306638
  37626238356236306531666364623832663164396664666665623133623235336566663665333033
  36313236633731313836326563306336383535623462323830623366383639313030303065306234
  64643133353537623937633035376462393561613035353533333032613164613432333738666665
  62326465346636663665316338623533653436626437323337663362366533366461356435633237
  66656563633139313865663635666231346666303633306634326265313739396430313364363064
  31383539366435376135343134626230313633373532396166643262333565386636346233326539
  33333164353437373464633166643130613837306539343562393932316136343763323734393635
  64333130613561363338313838326138363339663134623430616336666338313465613932616232
  31336431383163316138393937613564386562616133303837333839643262613664313661393735
  64373261643633613933353463653939393434623161383433646631303232643533636265303530
  34623136316638343434363739643863633563346363613531343537306538653465363132313735
  38396162646464663130373330623533663765333630366265623136336438633164396634303261
  65613537643366363761646632326366633536386634393438393566363432613637623432383338
  33353762363333396631376137373138633339663635646363653534666533363362363239363435
  31633261363632663531363639386165633936343530643731623063313761323664393237363336
  64366532633435343235613663393234666664386239636366363538643432353261643065303538
  33343861623236646263626261306137613962326561636361303430636133346634356366626335
  35353463373764643731336533383538366236326637623166306433346462363161366661393735
  62333633363039313462396264343565303530386264313931616335306130646163373039306138
  62373066353033313766316361323830393136313563343031303735643838353337663034643061
  63396535366264313532356430323131386466333832393131643162653236303832326135396564
  36323163313765323263383134383566666436383835396132633763396564306535616138343934
  34333639666431366630653938633666656666626531313738316133323961336237666266353930
  37636337323762316235373930363466393436356665316432316564613339666530623935373239
  33336166613134393439646566363339373135653863633035323861653961643137353833363639
  36336137353039316439313835663761363234386539646263646266636530656261343137353165
  39336637653736343163303963383961653566663465333639306334356130653834616635653535
  35353137653337613234613562643136666533356164306464306336313536343534366532363938
  37303965336361386366333437663833646635386535623532396136343334396531666662356333
  31626164333430303735633636666134623866346439376362396364623263633133633730656437
  63356336373266316638336665646561663763376665626135636436353937623065633536626639
  35363538623830646439656339366564316536643335316366613637323937663839626266386465
  61613238333132363132303362313233313039376663343731356565306232366365643530366234
  64646464373163316637653665646433303133366265393964363061633461636161653964613165
  63336634303431323638376337363165623536313536323837316238393139303535303764626135
  32616662656662656139396637633466363536646232643339373032303666633433356534353664
  65393138613830303336336239633762636632396337356533366239643037366164323633346631
  66663338346234346538376464353865633065623539333536396335396462643436353333396566
  35313931343762626631373663383064336437653235303365656433613337613834616264303035
  36636233313834373233333430303735636131393065666235393437656436343537333838313734
  33366565333365323335313735646131666434313832656431626535303364313137396366656537
  61653564396436616662316238346639343833656436653665643338643230313438663230396633
  66323462633266653233663038376564393937356234313732303631373333303135323065376363
  63333333633366653464353064663937626431636565353438626633353431303339333039623933
  36353330653231616634393636313861613133633339616465646335613865643363323739383264
  63636137663335393035323335663635326437356563336531333530353632646532656531386138
  38643733633464326137363163356633643239633334393965346632633033336266363661376131
  36356330346233663234333563376131326533303866623233636561343236646333643565643765
  62396533396631323366373166643535383230323264653962646234653734306361343866633638
  30383631363736306339303232376363373666613536313466346164393130656430313639383464
  35343965633965316134396462633438386333653830613662623539343532336563356130373565
  62353561386239383332316462393266363366373264376532613433393432656336636264643962
  66646265306164316138363932393537663335623031363164393865643030646230303537393563
  62313739636633623561653964383064303037373964333836393964356134633965353165303939
  34363032616336396362326437383263386130613563626137656237656439623963333236643238
  32306363383062393239623731303739353331306632366366326266323662343963653161616461
  31353339623766633131363466366562343533333666353330353463313131386236323039666530
  63353533333839326430633830386633303566353038386335313530343636313063616530623639
  35336362353331633839643462633363313433383632353634383863383436663965636665306630
  64373532306564363234333065373732303630303638636634633434326265373465363863336364
  34633235363830373638346335353665313363386435383062663433326537653165623135393165
  32643132343431643430336433636561396232633339643331316631326433383630363330396330
  39643065366634353635386233386136313236326565643333353362643530376563393638643635
  38626439393636643532396361666461656536336466303763396166613431366436303637633166
  36303535366339383831666531383732643138623532343165343864346462333531366535346563
  36633435653737373935613434386138303061373862313266323838623732663233616361666263
  37346138303538613833356239613831316463333164306161373965656535326635393332303363
  62356332663139363238

...
